src/problem.impl.cc

Problem::finishSolveStepByStep() called problemSolver::solve()

Correct mistake in finishSolveStepByStep()

---

idl/hpp/corbaserver/problem.idl
src/hpp/corbaserver/problem_solver.py
src/problem.impl.cc
src/problem.impl.hh

1. Locked Joint manipulation has been moved from hpp-manipulation to hpp-core.
2. Right hand side of constraints in config projector can now be set by interface methods.

Handle locked joints and bind right hand side related methods

---

.gitlab-ci.yml
README.md
tests/CMakeLists.txt
tests/robot.py

Hi,
Tests have been disabled by 1971709d5f39e495e5a0b09c2d75953b02801c5a. This PR enable them again, and almost fix them.
I still have 2 issues:
- omniidl creates the `build/src/hpp/corbaserver/hpp/corbaserver` folder, which really looks like a mistake, so I remove it before launching tests: `mkdir build; cd build; cmake ..; make -j8; rm -rf src/hpp/corbaserver/hpp; make test` -> raise #56 
- the test is passing on my desktop computer, but I can't get it work for now on the CI, probably because of some issues with omniNames & docker -> raise #57

fix tests, add .gitlab-ci.yml & badges

---

src/servant-base.hh

With an explicit cast from `shared_ptr` to `bool.
While here, rename `paths`' `print` to `show`, as defining `print` can raise a `SyntaxError` in python 2. I don't understand why this error does not appear on 16.04. My guess is that the generated file is not called properly.
Another error prevents the test `py-robot` to pass, but this seems less trivial, so I'm opening a separate issue.

fix build in c++11

---

src/problem.impl.cc

LockedJoint instances are handled as Implicit instances. Requires humanoid-path-planner/hpp-core#185.

Update to modification in hpp-core

---

NEWS
doc/porting-from-4-to-5.hh
idl/hpp/corbaserver/obstacle.idl
idl/hpp/corbaserver/robot.idl
src/hpp/corbaserver/problem_solver.py
src/hpp/corbaserver/robot.py
src/obstacle.impl.cc
src/obstacle.impl.hh
src/robot.impl.cc
src/robot.impl.hh

- formerly, urdf and srdf files needed to be in neighbor directories:
- package://pkg/[urdf|srdf]/.../robot[urdfSuffix|srdfSuffix].[urdf|srdf].
- Now one filename is given for the urdf file and one filename for the srdf
file.
Porting notes are provided in the html documentation.

Modify the way urdf and srdf files are handled

---

include/hpp/corbaserver/server.hh
src/server.cc

This fixes the issue of lost connection when a network interface goes down.
@JasonChmn when this is ready, using `hppcorbaserver --host localhost` should fix your problem.

Make ORB endPoint parameterizable.

---

src/problem.impl.cc

`movePathToProblem` was crashing without explicit error message when `jointNames` contains fixed joints. 
By the way, I would like to add an option to this method to also copy the extraDof. I will take a look at this later.

movePathToProblem: fix crash when using fixed joint

---

src/CMakeLists.txt
src/hpp/utils.py
tests/CMakeLists.txt
tests/utils.py

This was first put in https://github.com/humanoid-path-planner/hpp-rbprm-corba/commit/ef9021deff6105f6388d2f14b101675f512aa387 but after discussions with @florent-lamiraux this can probably bu usefull in other places, like hpp-corbaserver. The py-robots test could also be re-written with this.

Add a ServerManager utility context.

---

src/problem.impl.cc

- methods formerly taking const references to Problem as input now take
shared pointer to const Problem.
This PR requires https://github.com/humanoid-path-planner/hpp-core/pull/235.

Update to modifications in hpp-core

---

include/hpp/corbaserver/servant-base.hh

this commit remove some parameter shadowing warnings in
the code generated by omniidl.

[servant-base.hh] Rename member s -> s_.

---

include/hpp/corbaserver/conversions.hh

Without this, hpp-rbprm-corba build fails with:
```
FAILED: src/CMakeFiles/rbprm-corba.dir/rbprmbuilder.impl.cc.o
/usr/lib/ccache/bin/g++ -DBOOST_ALL_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_MPL_LIMIT_LIST_SIZE=30 -DBOOST_MPL_LIMIT_VECTOR_SIZE=30 -DBOOST_SERIALIZATION_DYN_LINK -DBOOST_THREAD_DYN_LINK -DCURVES_WITH_PINOCCHIO_SUPPORT -DHPP_FCL_HAS_OCTOMAP -DHPP_FCL_HAVE_OCTOMAP -DOCTOMAP_MAJOR_VERSION=1 -DOCTOMAP_MINOR_VERSION=9 -DOCTOMAP_PATCH_VERSION=6 -DPINOCCHIO_WITH_HPP_FCL -DPINOCCHIO_WITH_URDFDOM -Drbprm_corba_EXPORTS -I. -Iinclude -I../include -Isrc -isystem /usr/include/cddlib -isystem $ROBOTPKG/install/include -isystem /usr/include/eigen3 -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion -fdiagnostics-color=always -fPIC …
```

disambiguate ComparisonTypes_t

---

idl/hpp/corbaserver/problem.idl
src/hpp/corbaserver/robot.py
src/problem.impl.cc
src/problem.impl.hh

- [python] allow to set a mask for the COM constraint,
- [problem.idl] do not bind createStaticStabilityConstraint anymore.
This method is better implemented in hpp-manipulation-corba.

Improve static stability constraints

---

idl/hpp/corbaserver/tools.idl
include/hpp/corbaserver/server.hh
src/problem.impl.cc
src/server.cc

This PR adds the functions that sit next to `createContext`, that allows to work on several problems in parallel. The behavior of the new functions should be clear given their names.
While here, I add a commit which was on my devel branch when I left LAAS. I don't remember why I did that (the original commit is 1 year and 7 months ago...)

Add getContexts and deleteContext to the main server

---

src/hpp/utils.py

Fixes #178
This code now works:
```python
from hpp.utils import ServerManager
import hpp.corbaserver
with ServerManager():
cl1 = hpp.corbaserver.Client()
with ServerManager():
cl2 = hpp.corbaserver.Client()
```

Fix how hppcorbaserver is killed in ServerManager

---

src/hpp/corbaserver/client.py
src/hpp/corbaserver/tools.py
tests/CMakeLists.txt
tests/hppcorbaserver.sh
tests/port.py

When creating a client, environment variable HPP_PORT was not really
taken into account. This commit fixes this issue and allows to control
parallel instances of hppcorbaserver on different ports only by specifying
variable HPP_PORT.

Better handle default port

---

src/server.cc
tests/CMakeLists.txt
tests/delete_servant.py

When an Python CORBA object is `wrap_delete` twice, after one of the two is deleted by Python, the corresponding servant in C++ gets deleted. When the second is deleted, an exception is raised. Sadly, at the moment, in Python, it is not possible to count the number of reference to a C++ servant so it is hard to avoid such situation.
This PR bypasses the issue by not raising an error when trying to delete an already deleted object. This should be safe since there is semantically no work to do to delete an already deleted object.
Another possible solution is to catch the exception in the `_Deleter` class in Python.

avoid throwing an exception with deleting twice a servant.

---

tests/CMakeLists.txt

because CI gets a very high rate of
> omniORB.CORBA._omni_sys_exc: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

test: run py-port in serial

---

src/hpp/corbaserver/tools.py

import CORBA at the beginning of the file instead of in methods.

[tools] Remove error messages when exiting python.

---

include/hpp/corbaserver/server.hh
src/hpp-corbaserver.cc
src/server.cc

This PR needs https://github.com/humanoid-path-planner/hpp-util/pull/57.
Logs can be enabled or disabled using, e.g.,
```
hppcorbaserver --benchmark --verbosity 50
```
`hppcorbaserver --help` returns
```
Usage: hppcorbaserver [options] ...
--name <name>      
--host <host>      
--port <port>      
--help             
--verbosity <level>	where level is a positive integer between 0 (no logs) to 50 (very verbose).
--benchmark        	enable benchmarking (written in the logs).
--single-thread    
--multi-thread     
Environment variables:
- HPP_LOGGINGDIR: change the directory where logs are written.
- HPP_HOST: change the default host.
- HPP_PORT: change the default port.
```

Add CLI arguments to toggle logging.

---

idl/hpp/core_idl/paths.idl
src/hpp/corbaserver/tools.py

Exception raised in wrap_delete can be sometimes be CORBA.UNKNOWN. Maybe catching all CORBA exception is a bit too large though I don't know exactly what should be caught.

Expose path::Hermite + exceptions in wrap_delete

---

CMakeLists.txt
cmake-modules/omniidl/cxx_impl/template.py
idl/hpp/common.idl
idl/hpp/corbaserver/tools.idl
idl/hpp/core_idl/_constraints.idl
idl/hpp/core_idl/distances.idl
idl/hpp/core_idl/path_validations.idl
idl/hpp/core_idl/steering_methods.idl
idl/hpp/pinocchio_idl/robots.idl
include/hpp/corbaserver/read-write-lock.hh
include/hpp/corbaserver/servant-base.hh
include/hpp/corbaserver/server.hh
src/problem.impl.cc
src/robot.impl.cc
src/server.cc
tests/CMakeLists.txt
tests/problem.py
tests/robot.py

The PR changes:
- Follows https://github.com/humanoid-path-planner/hpp-pinocchio/pull/188.
- Add function `persistantStorage` to all IDL objects to allow the memory not to be owned by the servant.
- Add functions to better manage the memory:
- `deleteExpiredServants` removed servants whose object has already been deleted.
- `getAllServants` returns a list of object IDs that allows to access all the objects from Python.
- add a mutex to access the servant maps.

Pass computation flag to Device::computeForwardKinematics

---

src/CMakeLists.txt

For a mysterious reason, this directory is not created anymore and make installation from scratch fail.

[cmake] Create directory where omniidl will produce files.

---

idl/hpp/corbaserver/obstacle.idl
src/obstacle.impl.cc
src/obstacle.impl.hh

This PR adds two functions to *obstacle* IDL. The functions allow to load a point cloud either from an octomap file or from a Nx3 matrix. The functions allows to update the point cloud in place.
> [!NOTE]
> OmniORB has a limit on the size of the messages that can be sent. If that limit is reached (which is not hard with a point cloud), the limit should be increased. See doc of `loadPointCloudFromPoints` for more info.

Add function to load a point cloud as obstacle.

---

src/robot.impl.cc

This issue arises on PAL Ubuntu22.04 "alum".
```
$ gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ cmake --version
cmake version 3.22.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
cmake output: `-- C++ standard sufficient: Minimal required 14, currently defined: 17`

Fix pinocchio include order issue.
