humanoid-path-planner/hpp-corbaserver

idl/hpp/corbaserver/problem.idl
update relatively to commit 6b152049565fb9d2183ae2d7bddfc0598ef203a7
of hpp-core
=> python binding to choose configuration shooter type

CMakeLists.txt, doc/Doxyfile.extra.in, idl/hpp/corbaserver/problem.idl, include/hpp/corbaserver/doc.hh, include/hpp/corbaserver/fwd.hh, include/hpp/corbaserver/problem-solver-map.hh, include/hpp/corbaserver/server.hh, src/CMakeLists.txt, src/hpp-corbaserver.cc, src/hpp/corbaserver/__init__.py, src/hpp/corbaserver/benchmark.py, src/obstacle.impl.cc, src/obstacle.impl.hh, src/problem.impl.cc, src/problem.impl.hh, src/robot.impl.cc, src/robot.impl.hh, src/server.cc
- Add python class Benchmark
- Add map of ProblemSolver
=> Benchmark and map of ProblemSolver

idl/hpp/corbaserver/problem.idl, src/hpp/corbaserver/robot.py, src/problem.impl.cc, src/problem.impl.hh
Update to pull request #46 in hpp-core
=> Idl request Problem::directPath now return validation report

idl/hpp/corbaserver/problem.idl, src/hpp/corbaserver/problem_solver.py, src/problem.impl.cc, src/problem.impl.hh
see Pull request https://github.com/humanoid-path-planner/hpp-core/pull/54
=> add python binding in order to choose distance type

README.md
Add troubleshooting section for corba::transient error (copied from gepetto-viewer-corba readme)
=> update readme : add troubleshooting section

idl/hpp/corbaserver/robot.idl, include/hpp/corbaserver/conversions.hh, include/hpp/corbaserver/fwd.hh, src/conversions.cc, src/problem.impl.cc, src/robot.impl.cc, src/robot.impl.hh
Needs humanoid-path-planner/hpp-pinocchio#44
=> Use class Frame

include/hpp/corbaserver/conversions.hh, src/conversions.cc, src/problem.impl.cc, src/robot.impl.cc
Check that input configuration are normalized properly.
Needs humanoid-path-planner/hpp-pinocchio#45
=> Homogenize checks of input configuration

doc/Doxyfile.extra.in, idl/hpp/corbaserver/problem.idl, idl/hpp/corbaserver/robot.idl, src/hpp/corbaserver/client.py, src/hpp/corbaserver/robot.py, src/problem.impl.cc, src/problem.impl.hh, src/robot.impl.cc, src/robot.impl.hh
=> Add Problem.getConstraintDimensions + miscellaneous

src/hpp/corbaserver/robot.py
- computes which degrees of freedom are saturated for a given configuration.
=> Add method getSaturated to python class Robot

idl/hpp/corbaserver/obstacle.idl, idl/hpp/corbaserver/problem.idl, idl/hpp/corbaserver/robot.idl, src/obstacle.impl.cc, src/obstacle.impl.hh, src/problem.impl.cc, src/problem.impl.hh, src/robot.impl.cc, src/robot.impl.hh
When the number of paths becomes bigger than 32768, there is an overflow.
=> Change short in long in idl and C++ code.

idl/hpp/corbaserver/problem.idl, include/hpp/corbaserver/conversions.hh, src/CMakeLists.txt, src/hpp/corbaserver/problem_solver.py, src/problem.impl.cc, src/problem.impl.hh, src/robot.impl.cc
=> Bug fixes + changes for convenience

src/hpp/corbaserver/problem_solver.py, src/problem.impl.cc
1. Accept all types of frames for transformation constraints,
2. add method selectConfigurationShooter in problem_solver.py.
=> 2 modifications

src/hpp/corbaserver/problem_solver.py, src/problem.impl.cc
Update to modifications in hpp-core and hpp-constraints.
=> Refactor constraints

src/problem.impl.cc
@florent-lamiraux @rlefevre1 : This should fix your problem.
=> Fix assert in creation of transformation constraints.

idl/hpp/corbaserver/problem.idl, src/problem.impl.cc, src/problem.impl.hh
Related to https://github.com/humanoid-path-planner/hpp-constraints/pull/49
=> Add createIdentityConstraint.

src/robot.impl.cc
Follows https://github.com/humanoid-path-planner/hpp-pinocchio/pull/73
=> Update to API changes in hpp-pinocchio

CMakeLists.txt, src/problem.impl.cc
=>  Fix deprecated operator<== with int, to allow c++11 compat

src/hpp/corbaserver/tools.py
This follows https://github.com/Gepetto/gepetto-viewer-corba/pull/123, fixes unit tests, and requires https://github.com/jrl-umi3218/jrl-cmakemodules/pull/208
=> Don't overwrite __doc__ in python2

cmake-modules/omniidl/cxx_impl/main.py, idl/hpp/core_idl/_problem.idl, idl/hpp/core_idl/configuration_shooters.idl, idl/hpp/core_idl/path_planners.idl, src/robot.impl.cc
Follows https://github.com/humanoid-path-planner/hpp-core/pull/172
=> Update to API change. 

idl/hpp/corbaserver/tools.idl, include/hpp/corbaserver/client.hh, include/hpp/corbaserver/server-plugin.hh, include/hpp/corbaserver/server.hh, src/CMakeLists.txt, src/basic-server.hh, src/client.cc, src/hpp/corbaserver/client.py, src/server.cc
By default, the name service is not used.
Needs https://github.com/humanoid-path-planner/hpp-template-corba/pull/5
=> Allow bypassing the name service. 

idl/hpp/common.idl, idl/hpp/corbaserver/problem.idl, include/hpp/corbaserver/conversions.hh, src/conversions.cc, src/hpp/corbaserver/problem_solver.py, src/problem.impl.cc, src/problem.impl.hh
=> [problem.idl] Allow users to create LockedJoint with comparison types.

include/hpp/corbaserver/fwd.hh, src/problem.impl.cc
Requires https://github.com/humanoid-path-planner/hpp-constraints/pull/117.
=> Update to refactoring of convex-shape-contact in hpp-constraints

include/hpp/corbaserver/servant-base.hh, src/conversions.cc, src/problem.impl.cc
Requires https://github.com/humanoid-path-planner/hpp-constraints/pull/124.
=> Update to modifications in hpp-constraints

src/CMakeLists.txt, src/hpp/rostools.py
- add conversion from xacro to URDF,
- add function retrieve_resource.
=> Add some ROS utility functions.

doc/bindings/implicit.svg, idl/hpp/core_idl/paths.idl
- add documentation about the bindings
=> [core_idl] Bind method PathVector::flatten.

src/hpp/corbaserver/robot.py, src/hpp/corbaserver/tools.py
=> tools.createContext: add port argument

src/problem.impl.cc
Check that input index is not out of range.
=> [Problem] Fix bug in method nodesConnectedComponent.

CMakeLists.txt, cmake-modules/omniidl/cxx_impl/main.py, idl/hpp/core_idl/steering_methods.idl, include/hpp/corbaserver/conversions.hh, include/hpp/corbaserver/fwd.hh, include/hpp/corbaserver/object-map.hh, include/hpp/corbaserver/steering-method.hh, src/conversions.cc, src/object-map.cc, src/obstacle.impl.cc
=> Expose spline steering method

CMakeLists.txt
ref. https://github.com/humanoid-path-planner/hpp-corbaserver/pull/183#discussion_r1045612684
=> CMake: call findpython() when necessary

idl/hpp/corbaserver/problem.idl, src/problem.impl.cc, src/problem.impl.hh
This PR adds the ability to create constraint set and config projectors from Python.
=> Add function to create ConstraintSet and ConfigProjector

idl/hpp/pinocchio_idl/robots.idl, tests/problem.py, tests/robot.py
Add access to more functions of Device.
=> Expose more function of Device.

src/conversions.cc
Completed floatSeqSeqToMatrix to check the number of columns for every row. Throws an error when the actual number of columns is inconsistent with the expected one.
=> chekcing nb of cols for every row

idl/hpp/core_idl/path_validations.idl
Follows https://github.com/humanoid-path-planner/hpp-core/pull/322
=> allow to set the break distance in continuous validation

idl/hpp/core_idl/configuration_shooters.idl
Follows https://github.com/humanoid-path-planner/hpp-core/pull/326
=> expose UniformSeedable configuration shooter.

idl/hpp/core_idl/_problem.idl, idl/hpp/core_idl/path_planners.idl, include/hpp/corbaserver/conversions.hh, include/hpp/corbaserver/fwd.hh, src/conversions.cc, src/problem.impl.cc
Follows https://github.com/humanoid-path-planner/hpp-core/pull/330.
=> Update to removal of hpp::core::ConfigurationPtr_t

include/hpp/corbaserver/fwd.hh
ref https://github.com/humanoid-path-planner/hpp-fcl/pull/596
same as https://github.com/stack-of-tasks/pinocchio/pull/2323
=> non-breaking coal initial compatibility

src/problem.impl.cc
Requires https://github.com/humanoid-path-planner/hpp-pinocchio/pull/223.
=> Fix some compilation warnings

src/hpp/rostools.py
This pull request ensures compatibility with ROS2 without breaking compatibility with ROS1.
Should replace https://github.com/humanoid-path-planner/hpp-corbaserver/pull/252.
=> Use AMENT_PREFIX_PATH variable if defined.
